name = "HeteroTomo3D"
uuid = "263a12c5-01a3-4d1f-967a-ba60fd634f9a"
version = "1.0.0-DEV"
authors = ["YUN Ho <ho.yun@epfl.ch> and contributors"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
LinearAlgebra = "1.12.0"
SpecialFunctions = "2.7.1"
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
